def ejercicio1 ():
    number_grid = [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [0]
        ]
    
    print (number_grid[0][0])



def ejercicio2 ():
    number_group = [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [0]
        ]
    
    for group in number_group:
        for number in group:
            
            print (number)


ejercicio1 ()


